/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Otp as PrismaOtp, User as PrismaUser } from "@prisma/client";
import { EmailOtpCreateInput } from "../EmailOtpCreateInput";
import { Otp } from "./Otp";
import { OtpCreateInput } from "./OtpCreateInput";
import { PhoneOtpCreateInput } from "../PhoneOtpCreateInput";
import { EmailOtpValidationInput } from "../EmailOtpValidationInput";
import { PhoneOtpValidationInput } from "../PhoneOtpValidationInput";

export class OtpServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.OtpCountArgs, "select">): Promise<number> {
    return this.prisma.otp.count(args);
  }

  async otps(args: Prisma.OtpFindManyArgs): Promise<PrismaOtp[]> {
    return this.prisma.otp.findMany(args);
  }
  async otp(args: Prisma.OtpFindUniqueArgs): Promise<PrismaOtp | null> {
    return this.prisma.otp.findUnique(args);
  }
  async createOtp(args: Prisma.OtpCreateArgs): Promise<PrismaOtp> {
    return this.prisma.otp.create(args);
  }
  async updateOtp(args: Prisma.OtpUpdateArgs): Promise<PrismaOtp> {
    return this.prisma.otp.update(args);
  }
  async deleteOtp(args: Prisma.OtpDeleteArgs): Promise<PrismaOtp> {
    return this.prisma.otp.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.otp
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
  async GenerateEmailOtp(args: EmailOtpCreateInput): Promise<Otp> {
    throw new Error("Not implemented");
  }
  async GenerateOtp(args: OtpCreateInput): Promise<Otp> {
    throw new Error("Not implemented");
  }
  async GeneratePhoneOtp(args: PhoneOtpCreateInput): Promise<Otp> {
    throw new Error("Not implemented");
  }
  async ValidateEmailOtp(args: EmailOtpValidationInput): Promise<Otp> {
    throw new Error("Not implemented");
  }
  async ValidateOtp(args: OtpCreateInput): Promise<Otp> {
    throw new Error("Not implemented");
  }
  async ValidatePhoneOtp(args: PhoneOtpValidationInput): Promise<Otp> {
    throw new Error("Not implemented");
  }
}
